[tools]
# hadolint = "latest"
gemini-cli = "latest"
fd = "latest"
fzf = "latest"
neovim = "latest"
node = { version = "latest" }
perl = { version = "latest" }
python = { version = "latest" }
ripgrep = "latest"
shellcheck = "latest"
starship = "latest"
tmux = "latest"
usage = "latest"
gh = "latest"
