[tools]
# hadolint = "latest"
gemini-cli = "latest"
fd = "latest"
fzf = "latest"
node = { version = "latest" }
perl = { version = "latest" }
ripgrep = "latest"
shellcheck = "latest"
starship = "latest"
usage = "latest"
